<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Usuario\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idusuario', 'cpf', 'login', 'senha', 'email', 'userNivel', 'nivelMat', 'nivelCursos', 'nivelSysbm', 'permissaoSysbm', 'active', 'randomKey', 'regtime', 'salt', 'token');
        }

        return array('__isInitialized__', 'idusuario', 'cpf', 'login', 'senha', 'email', 'userNivel', 'nivelMat', 'nivelCursos', 'nivelSysbm', 'permissaoSysbm', 'active', 'randomKey', 'regtime', 'salt', 'token');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', array());

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', array());

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserNivel', array());

        return parent::getUserNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelMat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelMat', array());

        return parent::getNivelMat();
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelCursos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelCursos', array());

        return parent::getNivelCursos();
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getRandomKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRandomKey', array());

        return parent::getRandomKey();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegtime', array());

        return parent::getRegtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', array($idUsuario));

        return parent::setIdusuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', array($cpf));

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', array($login));

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserNivel($userNivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserNivel', array($userNivel));

        return parent::setUserNivel($userNivel);
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelMat($nivelMat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelMat', array($nivelMat));

        return parent::setNivelMat($nivelMat);
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelCursos($nivelCursos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelCursos', array($nivelCursos));

        return parent::setNivelCursos($nivelCursos);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function setRandomKey($randomKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRandomKey', array($randomKey));

        return parent::setRandomKey($randomKey);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegtime(\DateTime $regtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegtime', array($regtime));

        return parent::setRegtime($regtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelSysbm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelSysbm', array());

        return parent::getNivelSysbm();
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissaoSysbm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissaoSysbm', array());

        return parent::getPermissaoSysbm();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelSysbm($nivelSysbm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelSysbm', array($nivelSysbm));

        return parent::setNivelSysbm($nivelSysbm);
    }

    /**
     * {@inheritDoc}
     */
    public function setPermissaoSysbm($permissaoSysbm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermissaoSysbm', array($permissaoSysbm));

        return parent::setPermissaoSysbm($permissaoSysbm);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
